#!/usr/bin/env bash

kill_port() {
  if [[ $(lsof -t -i tcp:"$1") -gt 0 ]]; then
    lsof -t -i tcp:"$1" | xargs kill -15
    printf "\033[0;32mKilled process using port %s.\033[0m\n" "$1"
  else
    echo "Port is not currently in use."
  fi
}

kill_port "$1"
