#!/usr/bin/env bash

kill_port() {
  if [[ $(lsof -t -i tcp:$1) -gt 0 ]]; then
    lsof -t -i tcp:$1 | xargs kill -15
    printf "\033[0;32mKilled process using port $1.\033[0m\n"
  else
    echo "Port is not currently in use."
  fi
}

kill_port $1
